language: node_js
node_js:
  - "0.10"
  - "0.11"
  - "0.12"
  - "1.0"
  - "1.8"
  - "2.0"
  - "2.2"
  - "2.3"
before_install:
  - npm install -g grunt-cli
  - npm install coffee-script
before_script: grunt build
notifications:
  email:
    - snowyu.lee@gmail.com

